### ISSUE TITLE
recieving ERRORS;

### ISSUE THREAD

**Issue by ghost18881** [L1ghtn1ng/sslstrip#67]
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/k/.local/lib/python3.10/site-packages/twisted/internet/_resolver.py", line 189, in deliverResults
    resolutionReceiver.addressResolved(
  File "/home/k/.local/lib/python3.10/site-packages/twisted/internet/_resolver.py", line 305, in addressResolved
    self._deferred.callback(address.host)
  File "/home/k/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 874, in callback
    self._startRunCallbacks(result)
  File "/home/k/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 981, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/k/.local/lib/python3.10/site-packages/twisted/internet/defer.py", line 1075, in _runCallbacks
    current.result = callback(  # type: ignore[misc]
  File "/home/k/sslstrip/sslstrip/ClientRequest.py", line 77, in handleHostResolved
    path = self.getPathFromUri()
  File "/home/k/sslstrip/sslstrip/ClientRequest.py", line 55, in getPathFromUri
    return self.uri[7:] if self.uri.startswith("http://") else self.uri
builtins.TypeError: startswith first arg must be bytes or a tuple of bytes, not str

**Comment by y1174804262** [comment]
hey, I meet the same problem. Have you resolved it?

**Comment by L1ghtn1ng** [comment]
can you check the latest git code please?
